name: Indian Stock Market Tracker

on:
  schedule:
    # Run every hour during Indian market hours (9:15 AM - 3:30 PM IST)
    # IST is UTC+5:30, so 9:15 AM IST = 3:45 AM UTC, 3:30 PM IST = 10:00 AM UTC
    # Cron runs: 3:45, 4:45, 5:45, 6:45, 7:45, 8:45, 9:45 AM UTC (Monday-Friday)
    - cron: '45 3,4,5,6,7,8,9 * * 1-5'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  track-stocks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy gspread google-auth google-auth-oauthlib
    
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
    
    - name: Run Bollinger Bands Tracker
      run: |
        python bollinger_tracker.py
    
    - name: Clean up credentials
      if: always()
      run: |
        rm -f credentials.json
    
    - name: Log completion
      run: |
        echo "✅ Market tracker completed at $(date)"